version: '3.8'

services:
  app:
    build: .
    command: /start
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env

networks:
  default:
    external: true
    name: service-network